'use client';

import { useEffect, useRef, useState, useSyncExternalStore } from 'react';

import { fetchApiGenerateInvoice, fetchApiGetOrder } from '@/lib/api/client';
import type { InvoiceDto, InvoiceEntryDto, SkuResponse } from '@/lib/api/generated';
import { readSession, subscribeSession } from '@/lib/auth';
import { isUuid } from '@/lib/cold-chain';
import {
  STATUS_LABEL,
  addressLines,
  amountInWords,
  documentHeading,
  formatRupees,
  gapLabel,
  gapPrefix,
  gapSummary,
  generateOutcome,
  generateReason,
  gstRateLabel,
  invoiceDateLabel,
  lineQuantityLabel,
  notifyInvoicesChanged,
  parseRateDraft,
  placeOfSupplyLabel,
  readInvoiceDocument,
  refusalNeedsReread,
  regenerateNote,
  supplyLabel,
  taxRateLabels,
  taxTotals,
  unpricedLineIds,
  type InvoiceDocument,
  type Outcome,
} from '@/lib/invoices';
import { useInvoiceDetail, useInvoices } from '@/lib/use-invoices';
import { useSkuMap } from '@/lib/use-inbound';
import { roleHasCapability } from '@/lib/users';
import { ulid } from '@/lib/ulid';

import { DataTable, expandedRowId, type DataTableColumn } from '@/components/data-table/data-table';
import { FeedbackBanner } from '@/components/feedback/banner';
import { ReadFailure, Section, buttonClass, inputClass, labelClass, primaryClass, rowButtonClass } from '@/components/outbound/shell';

/**
 * The /compliance Invoices section (story 8-1). Invoices are generated by
 * the backend when an order dispatches; this surface reads them, prints
 * them, and — for `invoice.generate` holders — prices the lines that arrived
 * unpriced (channel orders, kit components) and generates an invoice for an
 * order the event path never covered (dispatched before 8-1 shipped, or a
 * data fault the delivery acknowledged).
 *
 * Pessimistic throughout (frontend guide §2): every figure on screen is the
 * server's, re-read after a mutation; nothing is computed here but labels.
 */

export function Invoices() {
  const sessioned = useSyncExternalStore(
    subscribeSession,
    () => readSession() !== null,
    () => null as boolean | null,
  );
  if (sessioned === null) return null;
  if (!sessioned) {
    return (
      <Section title="Invoices">
        <div className="text-(--muted-foreground)">Sign in to read the tenant&apos;s invoices.</div>
      </Section>
    );
  }
  return <InvoicesSessioned />;
}

function InvoicesSessioned() {
  const role = useSyncExternalStore(
    subscribeSession,
    () => readSession()?.user.role,
    () => undefined,
  );
  const canGenerate = roleHasCapability(role, 'invoice.generate');
  const list = useInvoices();
  const skus = useSkuMap();
  const [openId, setOpenId] = useState<string | null>(null);
  // A generate can insert a NEW row at the top of the newest-first keyset:
  // the table returns to page one and remounts so its Prev/Next state cannot
  // describe a page that no longer exists (frontend guide §1.4).
  const [pageEpoch, setPageEpoch] = useState(0);
  // A pricing success remounts the table (above) and, with the revision it
  // bumped, the pricing panel — so its outcome banner lives HERE, outside
  // the remounted tree, or it would vanish the moment it rendered.
  // Keyed to the invoice it describes and shown only while that invoice is
  // open — opening another invoice must not leave invoice A's "issued" banner
  // above invoice B (keyed derivation, not a reset effect — guide §1.5).
  const [panelOutcome, setPanelOutcome] = useState<{ invoiceId: string; outcome: Outcome } | null>(null);
  const shownOutcome = panelOutcome !== null && panelOutcome.invoiceId === openId ? panelOutcome.outcome : null;
  function onGenerated(settled?: { invoiceId: string; outcome: Outcome }) {
    setPanelOutcome(settled ?? null);
    list.onCursor(null);
    setPageEpoch((e) => e + 1);
    notifyInvoicesChanged();
  }

  const columns: DataTableColumn<InvoiceEntryDto>[] = [
    {
      key: 'invoiceNo',
      header: 'Invoice',
      render: (row) =>
        row.invoiceNo === null ? <span className="text-(--muted-foreground)">Unnumbered</span> : <span className="font-mono text-xs">{row.invoiceNo}</span>,
    },
    { key: 'status', header: 'Status', render: (row) => STATUS_LABEL[row.status] ?? row.status },
    { key: 'order', header: 'Order', render: (row) => <span className="font-mono text-xs">{row.orderId.slice(0, 8)}…</span> },
    { key: 'supply', header: 'Supply', render: (row) => supplyLabel(row.supplyType, row.placeOfSupply) },
    { key: 'total', header: 'Total', numeric: true, render: (row) => formatRupees(row.totalPaise) },
    {
      key: 'gaps',
      header: 'Gaps',
      render: (row) => <span className="text-xs">{gapSummary(row.gapKinds)}</span>,
    },
    {
      key: 'open',
      header: '',
      render: (row) => (
        <button
          type="button"
          className={rowButtonClass}
          aria-expanded={openId === row.id}
          aria-controls={expandedRowId(row.id)}
          onClick={() => setOpenId(openId === row.id ? null : row.id)}
        >
          {openId === row.id ? 'Hide' : 'View'}
        </button>
      ),
    },
  ];

  return (
    <Section title="Invoices">
      <div className="text-(--muted-foreground)">
        One GST invoice per dispatched order, generated when the order dispatches. An invoice
        waits as <em>awaiting data</em> until every line is priced, the place of supply resolves
        and a supplier GSTIN exists; it takes its number when it issues.
      </div>

      {canGenerate && <GenerateForOrder onGenerated={() => onGenerated()} />}

      {shownOutcome !== null && (
        <FeedbackBanner tone={shownOutcome.tone} word={shownOutcome.word} reason={shownOutcome.reason} />
      )}

      {list.state === 'failed' ? (
        <ReadFailure word="Invoices unavailable" reason={list.reason} onRetry={list.reload} />
      ) : (
        // The table stays MOUNTED while a page loads (the outbound-orders
        // pattern): its Prev/Next cursor is internal state, and swapping it
        // for a loading line on every page change would remount it onto
        // "page one" — Prev would never enable.
        <DataTable
          key={pageEpoch}
          columns={columns}
          rows={list.state === 'ready' ? list.data.items : []}
          nextCursor={list.state === 'ready' ? list.data.nextCursor : null}
          onCursor={list.onCursor}
          emptyMessage={list.state === 'loading' ? 'Loading invoices…' : 'No invoices yet — they are generated when orders dispatch.'}
          renderExpanded={(row) =>
            row.id === openId ? (
              <InvoiceDetail invoiceId={row.id} canGenerate={canGenerate} skus={skus} onGenerated={onGenerated} />
            ) : null
          }
        />
      )}
    </Section>
  );
}

/**
 * Generate an invoice for one dispatched order by id — the recovery path for
 * orders the event path never invoiced. The key is per DRAFT: reused across
 * retries of an unchanged id (a timeout after the server committed must
 * replay, not regenerate), cleared on any edit and on success.
 */
function GenerateForOrder({ onGenerated }: { onGenerated: () => void }) {
  const [orderId, setOrderId] = useState('');
  const [key, setKey] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [problem, setProblem] = useState<string | null>(null);
  const [outcome, setOutcome] = useState<Outcome | null>(null);
  const inFlight = useRef(false);

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    const session = readSession();
    if (session === null || inFlight.current) return;
    const id = orderId.trim().toLowerCase();
    if (!isUuid(id)) {
      setProblem('An order id is a 36-character UUID (8-4-4-4-12, hex, dashes) — check the paste.');
      return;
    }
    setProblem(null);
    const idempotencyKey = key ?? ulid();
    setKey(idempotencyKey);
    inFlight.current = true;
    setBusy(true);
    setOutcome(null);
    try {
      const { invoice } = await fetchApiGenerateInvoice(session.tenant.id, { orderId: id }, idempotencyKey);
      setOutcome(generateOutcome(invoice));
      setOrderId('');
      setKey(null);
      onGenerated();
    } catch (error) {
      setOutcome({ tone: 'rejected', word: 'Not generated', reason: generateReason(error) });
    } finally {
      inFlight.current = false;
      setBusy(false);
    }
  }

  return (
    <form onSubmit={submit} className="flex flex-col gap-1">
      <span className={labelClass}>Generate for a dispatched order</span>
      <div className="flex gap-2">
        <input
          className={inputClass}
          value={orderId}
          onChange={(e) => {
            setOrderId(e.target.value);
            setKey(null);
          }}
          placeholder="Order id (UUID)"
          // Room for a padded paste — the trim happens on submit; a 36-cap
          // would cut a pasted ' <uuid> ' before it.
          maxLength={64}
          spellCheck={false}
          aria-label="Order id"
        />
        <button type="submit" className={`${primaryClass} shrink-0`} disabled={busy}>
          {busy ? 'Generating…' : 'Generate'}
        </button>
      </div>
      {problem !== null && <div className="text-xs text-(--destructive)">{problem}</div>}
      {outcome !== null && <FeedbackBanner tone={outcome.tone} word={outcome.word} reason={outcome.reason} />}
    </form>
  );
}

function InvoiceDetail({
  invoiceId,
  canGenerate,
  skus,
  onGenerated,
}: {
  invoiceId: string;
  canGenerate: boolean;
  skus: Readonly<Record<string, SkuResponse>> | null;
  onGenerated: (settled: { invoiceId: string; outcome: Outcome }) => void;
}) {
  const detail = useInvoiceDetail(invoiceId);
  if (detail.state === 'failed') {
    return <ReadFailure word="Invoice unavailable" reason={detail.reason} onRetry={detail.reload} />;
  }
  if (detail.state === 'loading') {
    return <div className="text-(--muted-foreground)">Loading…</div>;
  }
  const invoice = detail.data;
  const document = readInvoiceDocument(invoice.document);
  if (document === null) {
    return (
      <FeedbackBanner
        tone="rejected"
        word="Document unreadable"
        reason="This invoice's document is not in a shape this screen recognises — it cannot be printed here."
      />
    );
  }
  const skuByCode = new Map(Object.values(skus ?? {}).map((sku) => [sku.code, sku]));
  const unpriced = unpricedLineIds(document);
  return (
    <div className="flex flex-col gap-3 py-1">
      <div className="flex flex-wrap items-center gap-2">
        <button type="button" className={buttonClass} onClick={() => window.print()}>
          Print
        </button>
        <span className="text-xs text-(--muted-foreground)">Revision {invoice.revision}</span>
      </div>
      <PrintableInvoice invoice={invoice} document={document} skuByCode={skuByCode} />
      {canGenerate && invoice.status !== 'voided' && (
        <PricingPanel
          key={`${invoice.id}-${invoice.revision}`}
          invoice={invoice}
          unpriced={unpriced}
          skus={skus}
          onGenerated={onGenerated}
        />
      )}
    </div>
  );
}

/**
 * The printable tax document. An invoice that has not issued prints as a
 * DRAFT, never as a tax invoice: it has no number and something still
 * blocks it. `data-print-root` scopes the print stylesheet to this element.
 */
function PrintableInvoice({
  invoice,
  document,
  skuByCode,
}: {
  invoice: InvoiceDto;
  document: InvoiceDocument;
  skuByCode: ReadonlyMap<string, SkuResponse>;
}) {
  const { header, seller, buyer, totals } = document;
  const heading = documentHeading(invoice.status);
  const byTax = taxTotals(document.lines);
  return (
    <article data-print-root className="flex flex-col gap-3 rounded-md border border-(--border) bg-(--background) p-4">
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div className="flex flex-col">
          <h3 className="text-base font-semibold">{heading.title}</h3>
          {heading.notice !== null && <span className="text-xs text-(--muted-foreground)">{heading.notice}</span>}
        </div>
        <div className="flex flex-col text-right text-xs">
          <span className="font-mono">{header.invoiceNo ?? 'Unnumbered'}</span>
          {header.issuedAt !== null && <time dateTime={header.issuedAt}>{invoiceDateLabel(header.issuedAt)}</time>}
          <span className="text-(--muted-foreground)">Order {header.orderRef}</span>
        </div>
      </div>

      <div className="grid gap-3 text-xs sm:grid-cols-2">
        <div className="flex flex-col">
          <span className="font-medium">Supplier</span>
          <span>{seller.name}</span>
          <span>GSTIN: {seller.gstin ?? '—'}</span>
          {addressLines(header.originAddress).map((line) => (
            <span key={line}>{line}</span>
          ))}
        </div>
        <div className="flex flex-col">
          <span className="font-medium">Recipient</span>
          <span>{buyer.name ?? '—'}</span>
          <span>GSTIN: {buyer.gstin ?? 'Unregistered'}</span>
          {addressLines(header.consigneeAddress).map((line) => (
            <span key={line}>{line}</span>
          ))}
        </div>
      </div>
      <div className="text-xs">
        Place of supply: {placeOfSupplyLabel(header.placeOfSupply)} ·{' '}
        {supplyLabel(header.supplyType, header.placeOfSupply)}
      </div>

      <div className="overflow-x-auto">
        <table className="w-full border-collapse text-xs">
          <thead>
            <tr className="border-b border-(--border) text-left">
              <th className="py-1 pr-2 font-medium">Item</th>
              <th className="py-1 pr-2 font-medium">HSN</th>
              <th className="data py-1 pr-2 text-right font-medium">Qty</th>
              <th className="data py-1 pr-2 text-right font-medium">Rate</th>
              <th className="data py-1 pr-2 text-right font-medium">Taxable</th>
              <th className="data py-1 pr-2 text-right font-medium">GST</th>
              <th className="data py-1 pr-2 text-right font-medium">CGST</th>
              <th className="data py-1 pr-2 text-right font-medium">SGST/UTGST</th>
              <th className="data py-1 text-right font-medium">IGST</th>
            </tr>
          </thead>
          <tbody>
            {document.lines.map((line) => {
              const sku = skuByCode.get(line.skuCode);
              const rates = taxRateLabels(line.gstBps, header.supplyType);
              return (
                <tr key={line.orderLineId} className="border-b border-(--border)">
                  <td className="py-1 pr-2">
                    {line.skuCode} — {line.skuName}
                  </td>
                  <td className="py-1 pr-2">{line.hsn ?? '—'}</td>
                  <td className="data py-1 pr-2 text-right">
                    {lineQuantityLabel(line.qtyMilli, line.uom, sku === undefined ? null : { uom: sku.uom, uomPrecision: sku.uomPrecision })}
                  </td>
                  <td className="data py-1 pr-2 text-right">
                    {formatRupees(line.ratePaise)}
                    {line.rateSource === 'manual' && <span className="text-(--muted-foreground)"> (manual)</span>}
                  </td>
                  <td className="data py-1 pr-2 text-right">{formatRupees(line.taxablePaise)}</td>
                  <td className="data py-1 pr-2 text-right">{gstRateLabel(line.gstBps)}</td>
                  <td className="data py-1 pr-2 text-right">
                    {formatRupees(line.cgstPaise)} <span className="text-(--muted-foreground)">@ {rates.cgst}</span>
                  </td>
                  <td className="data py-1 pr-2 text-right">
                    {formatRupees(line.sgstPaise)} <span className="text-(--muted-foreground)">@ {rates.sgst}</span>
                  </td>
                  <td className="data py-1 text-right">
                    {formatRupees(line.igstPaise)} <span className="text-(--muted-foreground)">@ {rates.igst}</span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <dl className="ml-auto grid grid-cols-2 gap-x-4 text-xs">
        <dt>Taxable value</dt>
        <dd className="data text-right">{formatRupees(totals.subtotal)}</dd>
        <dt>CGST</dt>
        <dd className="data text-right">{formatRupees(byTax.cgst)}</dd>
        <dt>SGST/UTGST</dt>
        <dd className="data text-right">{formatRupees(byTax.sgst)}</dd>
        <dt>IGST</dt>
        <dd className="data text-right">{formatRupees(byTax.igst)}</dd>
        <dt className="font-medium">Total</dt>
        <dd className="data text-right font-medium">{formatRupees(totals.payAble)}</dd>
      </dl>
      <div className="text-xs">Amount in words: {amountInWords(totals.payAble)}</div>

      {document.gaps.length > 0 && (
        <ul className="flex flex-col gap-0.5 text-xs" aria-label="Invoice gaps">
          {document.gaps.map((gap, index) => (
            <li key={`${gap.kind}-${gap.orderLineId ?? index}`}>
              <span className="font-medium">
                {gapPrefix(gap.kind)} — {gapLabel(gap.kind)}:
              </span>{' '}
              <span className="text-(--muted-foreground)">{gap.detail}</span>
            </li>
          ))}
        </ul>
      )}

      <div className="mt-4 flex flex-col items-end text-xs">
        <span>For {seller.name}</span>
        <span className="mt-8 border-t border-(--border) pt-1">Authorised signatory</span>
      </div>
    </article>
  );
}

/**
 * The `invoice.generate` panel: a rate input per line the SERVER lists as
 * unpriced (`gap.orderLineId` — an acceptance-priced line is never offered,
 * its override is a guaranteed 409), and a plain regenerate when nothing is
 * unpriced. Per-draft key: reused across retries of the unchanged draft,
 * cleared on any edit. Remounted per invoice revision (its `key`), so a
 * success that changed the document starts a fresh draft.
 */
function PricingPanel({
  invoice,
  unpriced,
  skus,
  onGenerated,
}: {
  invoice: InvoiceDto;
  unpriced: readonly string[];
  skus: Readonly<Record<string, SkuResponse>> | null;
  onGenerated: (settled: { invoiceId: string; outcome: Outcome }) => void;
}) {
  const labels = useOrderLineLabels(invoice.orderId, unpriced.length > 0, skus);
  const [texts, setTexts] = useState<Record<string, string>>({});
  const [key, setKey] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [problem, setProblem] = useState<string | null>(null);
  const [outcome, setOutcome] = useState<Outcome | null>(null);
  const inFlight = useRef(false);

  function labelOf(orderLineId: string): string {
    return labels[orderLineId] ?? `Line ${orderLineId.slice(0, 8)}…`;
  }

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    const session = readSession();
    if (session === null || inFlight.current) return;
    let rates: { orderLineId: string; ratePaise: number }[] = [];
    if (unpriced.length > 0) {
      const parsed = parseRateDraft(unpriced.map((id) => ({ orderLineId: id, label: labelOf(id), text: texts[id] ?? '' })));
      if (parsed.problem !== null) {
        // A new local problem supersedes an earlier refusal banner — leaving
        // both on screen would pin the old server refusal to the new draft.
        setOutcome(null);
        setProblem(parsed.problem);
        return;
      }
      rates = parsed.rates;
    }
    setProblem(null);
    const idempotencyKey = key ?? ulid();
    setKey(idempotencyKey);
    inFlight.current = true;
    setBusy(true);
    setOutcome(null);
    try {
      const { invoice: settled } = await fetchApiGenerateInvoice(
        session.tenant.id,
        rates.length === 0 ? { orderId: invoice.orderId } : { orderId: invoice.orderId, rates },
        idempotencyKey,
      );
      setKey(null);
      // The success banner is the section's (this panel remounts on the
      // revision the success bumped); only a refusal stays here, beside the
      // draft it refused.
      onGenerated({ invoiceId: invoice.id, outcome: generateOutcome(settled) });
    } catch (error) {
      setOutcome({ tone: 'rejected', word: 'Not generated', reason: generateReason(error) });
      // The refused line set is stale: re-read, as the refusal copy says
      // (the excursion-resolved precedent — the reload IS the recovery). The
      // detail refetch keeps this panel mounted (same revision), so the
      // banner stays beside the refreshed draft.
      if (refusalNeedsReread(error)) notifyInvoicesChanged();
    } finally {
      inFlight.current = false;
      setBusy(false);
    }
  }

  return (
    <form onSubmit={submit} className="flex flex-col gap-2 rounded-md border border-(--border) p-3">
      {unpriced.length > 0 ? (
        <>
          <div className="text-xs font-medium">Price the unpriced lines (₹ per base unit, before GST)</div>
          {unpriced.map((id) => (
            <label key={id} className="flex flex-col gap-1 sm:flex-row sm:items-center sm:gap-3">
              <span className="text-xs sm:w-56">{labelOf(id)}</span>
              <input
                className={`${inputClass} sm:max-w-40`}
                inputMode="decimal"
                value={texts[id] ?? ''}
                onChange={(e) => {
                  setTexts({ ...texts, [id]: e.target.value });
                  setKey(null);
                }}
                placeholder="125.50"
                aria-label={`Rate for ${labelOf(id)}`}
              />
            </label>
          ))}
        </>
      ) : (
        <div className="text-xs text-(--muted-foreground)">{regenerateNote(invoice.status)}</div>
      )}
      <div>
        <button type="submit" className={primaryClass} disabled={busy}>
          {busy ? 'Saving…' : unpriced.length > 0 ? 'Save prices and regenerate' : 'Regenerate'}
        </button>
      </div>
      {problem !== null && <div className="text-xs text-(--destructive)">{problem}</div>}
      {outcome !== null && <FeedbackBanner tone={outcome.tone} word={outcome.word} reason={outcome.reason} />}
    </form>
  );
}

/**
 * orderLineId → `SKU-CODE — name` through the order read and the SKU map,
 * for the pricing labels. Enrichment only: a failed read falls back to the
 * short line id (the panel still works — the ids are the server's).
 */
function useOrderLineLabels(
  orderId: string,
  enabled: boolean,
  skus: Readonly<Record<string, SkuResponse>> | null,
): Readonly<Record<string, string>> {
  const [lines, setLines] = useState<{ orderId: string; skuByLine: Record<string, string> } | null>(null);
  useEffect(() => {
    const session = readSession();
    if (!enabled || session === null) return;
    let cancelled = false;
    (async () => {
      try {
        const { order } = await fetchApiGetOrder(session.tenant.id, orderId);
        if (!cancelled) {
          setLines({ orderId, skuByLine: Object.fromEntries(order.lines.map((line) => [line.id, line.skuId])) });
        }
      } catch {
        // Enrichment: the short-id fallback renders instead.
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [orderId, enabled]);
  if (lines === null || lines.orderId !== orderId) return {};
  const labels: Record<string, string> = {};
  for (const [lineId, skuId] of Object.entries(lines.skuByLine)) {
    const sku = skus?.[skuId];
    if (sku !== undefined) labels[lineId] = `${sku.code} — ${sku.name}`;
  }
  return labels;
}
